### ISSUE TITLE
Error exception typo

### ISSUE THREAD

**Issue by ghostwords** [mozilla/geckodriver#1032]
For example, an error message might look like "foo was not **a the** name of a known capability or a valid extension capability" (emphasis mine).

Following up on https://github.com/SeleniumHQ/selenium/issues/3918.

## System
* Version: geckodriver v0.16.1
* Platform: Ubuntu 14.04 (Travis)
* Firefox: Mozilla Firefox 53.0
* Selenium: Selenium Python bindings 3.4.0

**Comment by whimboo** [comment]
@ghostwords you are using a very outdated release of geckodriver. Does the same still show up when using geckodriver 0.19.1?

**Comment by ghostwords** [comment]
Regarding the typo, could you point me to where in the code this string might be found?

**Comment by whimboo** [comment]
No, because I cannot find it. But even looking at the source of 0.16 I have a hard time finding it. @andreastt, can we assume that this issue has already been fixed in the past?

**Comment by andreastt** [comment]
I tried looking for it some time ago, but could not find the string anywhere in our source code. I’m rather confident this issue has been fixed already.

Unfortunately recent geckodriver versions do not support Firefox 52. I encourage you to upgrade to Firefox Nightly, since geckodriver is in a pre-release state.

**Comment by ghostwords** [comment]
We would like to test [our add-on](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/) on all supported Firefox platforms, of which Firefox ESR is one. Unless I misunderstand you, it's not a matter of us upgrading; it's about testing on officially supported platforms that our users are on.

Firefox ESR is currently based on Firefox 52, an old but an officially supported Firefox release. It is unfortunate geckodriver >= 0.18 does not support it.

**Comment by andreastt** [comment]
As I said, because geckodriver is in a pre-release state we don’t support all released Firefox versions.

**Comment by whimboo** [comment]
Just to add some info here... The webdriver spec has been changed a lot in the past months, and is still not in the released state (it will most likely happen end of December). As result we had to change a lot in our code, which in some cases makes it very difficult to keep backward compatibility. We are sorry about, but the time investment for keeping compat with those old builds doesn't pay off.

Something you should consider is to use different versions of geckodriver. Given that you want to test all supported releases you could use 0.16 for Firefox esr52, and 0.19.1 for Firefox 56 and the upcoming 57 release.

When you had a chance to use the newest driver release let us know if this failure is still present for you. Maybe it's coming from somewhere else but not geckodriver. Thanks.

**Comment by ghostwords** [comment]
Thank you for the explanation and the excellent suggestion! I'll let you know if I see the typo again. (I originally reported it to Selenium: https://github.com/SeleniumHQ/selenium/issues/3918.)

**Comment by whimboo** [comment]
Ok, I had another look and indeed it's a spelling error in the webdriver crate:

https://dxr.mozilla.org/mozilla-central/rev/b5a3b8ef6902998507fc881b6d628b055457fe31/testing/webdriver/src/capabilities.rs#113

I filed [bug 1414256](https://bugzilla.mozilla.org/show_bug.cgi?id=1414256) to get this fixed.

**Comment by aldaris** [comment]
The corresponding Firefox bug is now resolved, probably this can be closed as well.

**Comment by whimboo** [comment]
Thanks Peter for reminding me.
