### ISSUE TITLE
Firefox 58 - GeckoDriver 20 - Web page opening but then saying Element not found (when it is there)

### ISSUE THREAD

**Issue by thomhurst** [mozilla/geckodriver#1216]
## System

* Version: 20.0
* Platform: Windows 10
* Firefox: 58
* Selenium: 3.11

## Stacktrace

Mar 14, 2018 11:38:21 AM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
1521027503611	geckodriver	INFO	geckodriver 0.20.0
1521027503633	geckodriver	INFO	Listening on 127.0.0.1:40566
1521027504383	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\Firefox.exe" "-marionette" "-profile" "C:\\Users\\TOM~1.LON\\AppData\\Local\\Temp\\3\\rust_mozprofile.rloP4ypUZSaX"
1521027505608	Marionette	INFO	Enabled via --marionette
1521027507874	Marionette	INFO	Listening on port 21887
1521027508192	Marionette	WARN	TLS certificate errors will be ignored for this session
Mar 14, 2018 11:38:28 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1521027526546	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "Certificate checks failed. See previous errors for details."  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: validateCert :: line 113"  data: no]
org.openqa.selenium.NoSuchElementException: Can't find the element By.cssSelector:

[Child 46612, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

1521027532668	geckodriver::marionette	ERROR	Failed to stop browser process

Firefox is opening up and navigating to the correct webpage, but then is unable to interact with any elements on the page. It fails with an exception saying can't find the element, however the element is clearly there.
This test passes on Chrome.

**Comment by S-Kerrigan** [comment]
You can update your Selenium library? Actual version in current day 3.8.1

**Comment by thomhurst** [comment]
If you look here, 3.11 is the latest: https://www.seleniumhq.org/download/

**Comment by whimboo** [comment]
@thomhurst this is not a trace log of geckodriver/marionette. Please see https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to retrieve one. Also it would be great to see the code you were using here, if possible minimized as best as possible. Thanks.

**Comment by funkvn** [comment]
Hello everybode, I have a similar problem: Newer version of Selenium Standalone Server than 3.4.0 does not work with geckodriver 0.20. 

I tested this wrong behavoiur with Firefox 59.0.1, geckodriver 0.20 and Selenium 3.3.1, 3.5.3, 3.6.0, 3.8.1, 3.9.1 and 3.11.0 on Windows 7.

As described, the browser is controlled as expeced and shows the right content, but returns a failure.
An concurrent runned cromeddriver (2.37) works as desired.

How can I help you to provide a solution?

**Comment by whimboo** [comment]
As requested already above a trace log would be needed, and as best also some code.

**Comment by elacang** [comment]
Hey guys,

I am getting the _1523127124947	geckodriver::marionette	ERROR	Failed to stop browser process_ when I do driver.close() / driver.quit() in my after hook.

Java 8
Selenium 3.11
Firefox 59.0.2

Here's the TRACE after I execute quit
`1523127124348	webdriver::server	DEBUG	-> DELETE /session/a2006c78-1461-a74e-afb2-a52340d9050b/window 
1523127124348	geckodriver::marionette	TRACE	-> 17:[0,39,"close",{}]
1523127124348	Marionette	TRACE	0 -> [0,39,"close",{}]
1523127124350	Marionette	TRACE	0 <- [1,39,null,[]]
1523127124351	geckodriver::marionette	TRACE	<- [1,39,null,[]]
1523127124351	webdriver::server	DEBUG	Last window was closed, deleting session
1523127124351	webdriver::server	DEBUG	Deleting session
1523127124351	geckodriver::marionette	TRACE	-> 38:[0,40,"quit",{"flags":["eForceQuit"]}]
1523127124356	Marionette	TRACE	0 -> [0,40,"quit",{"flags":["eForceQuit"]}]
1523127124356	Marionette	DEBUG	New connections will no longer be accepted
1523127124412	Marionette	TRACE	0 <- [1,40,null,{"cause":"shutdown"}]
1523127124434	geckodriver::marionette	TRACE	<- [1,40,null,{"cause":"shutdown"}]
1523127124444	Marionette	DEBUG	Closed connection 0
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1523127124532	Marionette	DEBUG	Received observer notification "xpcom-shutdown"
1523127124532	Marionette	DEBUG	Resetting recommended pref browser.newtabpage.enabled
1523127124534	Marionette	DEBUG	Resetting recommended pref browser.newtabpage.introShown
1523127124534	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1523127124536	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1523127124947	geckodriver::marionette	ERROR	Failed to stop browser process
1523127124977	webdriver::server	DEBUG	<- 200 OK {"value": []}`

**Comment by andreastt** [comment]
@elacang Can you please file a separate bug?

**Comment by whimboo** [comment]
There is no bug/issue needed. @elacang just download the latest release geckodriver 0.20.1 and you will see a correct message in the log. Also this is totally unrelated to this issue.

**Comment by whimboo** [comment]
Again, if no-one comes up with a trace log as requested very early on this issue we will have to close it.

**Comment by parshudhole** [comment]
Hello ,
    I am attaching gecko driver logs (trace logs ) from my Mac machine ,also below see the logs 
from my tests where it failed to find the element 

2018-05-28 11:49:14,043 | 6700 | 123145385259008 | ElementOperation | elementoperations.py | 49 | INFO | Clicked on element successfully. id='url'
2018-05-28 11:49:14,072 | 6700 | 123145385259008 | ElementOperation | elementoperations.py | 52 | DEBUG | Failed to find element on UI with name='uploadFile': Error - A WebDriveException occurred : - Message: Cannot click <input type=file> elements

Kindly refer the attached relevant geckdriver logs .
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2043929/geckodriver.log)

**Comment by whimboo** [comment]
@parshudhole please upgrade geckodriver to 0.20.1 and create a new tracelog. 0.18 is kinda outdated and no longer supported.

Also has your system IPv6 enabled? Can you please check to which address `localhost` resolves to?

**Comment by parshudhole** [comment]
@whimboo I already tested with geckodriver 0.20.1 ,attaching the geckodriver logs for your reference here.
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2048851/geckodriver.log)

IPV4 address is assigned  but the ‘configure IP6’ setting is set to ‘Link-Local only’ on my Mac OSX.
localhost is resolved to 127.0.0.1

**Comment by whimboo** [comment]
@parshudhole this is not a trace log. Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to provide one.

**Comment by HristoTest** [comment]
@whimboo Hi, it seems that i have same issue by using geckdoriver. 

Test:  Fill-up a simple word in google search bar on https://google.com

Scenario:Test Google                
Given I am on the homepage         # Drupal\DrupalExtension\Context\MinkContext::iAmOnHomepage()
And I wait for "2" seconds              # FeatureContext::iWaitForSeconds()
And I fill in "lst-ib" with "toto"         # Drupal\DrupalExtension\Context\MinkContext::fillField()
      Form field with id|name|label|value|placeholder "lst-ib" not found. (Behat\Mink\Exception\ElementNotFoundException)

Tools ; selenium standalone server : 3.12.0 / geckodriver: 0.21.0 (win64) / firefox 60.0.2  <br/>
![screen shot 06-18-18 at 06 03 pm](https://user-images.githubusercontent.com/40364448/41548008-035ca076-7322-11e8-8d52-d7a980a4b892.PNG)

I can perform the same test correctly with chromedriver.

Selenium console: 
17:58:08.510 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
17:58:08.511 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@6b8efa0
17:58:08.511 INFO - /session: Executing POST on /session (handler: BeginSession)
17:58:08.512 INFO - Capabilities are: Capabilities {deviceType=tablet, selenium-version=2.31.0, browserVersion=60.0.2, browser=firefox, name=Behat feature suite, browserName=firefox, deviceOrientation=portrait, ignoreZoomSetting=false, platformName=ANY, version=9, platform=ANY, tags=[4B80902, PHP 7.2.2], }
17:58:08.512 INFO - Capabilities {deviceType=tablet, selenium-version=2.31.0, browserVersion=60.0.2, browser=firefox, name=Behat feature suite, browserName=firefox, deviceOrientation=portrait, ignoreZoomSetting=false, platformName=ANY, version=9, platform=ANY, tags=[4B80902, PHP 7.2.2], } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
17:58:08.513 INFO - Capabilities {deviceType=tablet, selenium-version=2.31.0, browserVersion=60.0.2, browser=firefox, name=Behat feature suite, browserName=firefox, deviceOrientation=portrait, ignoreZoomSetting=false, platformName=ANY, version=9, platform=ANY, tags=[4B80902, PHP 7.2.2], } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1529337488540   geckodriver     INFO    geckodriver 0.21.0
1529337488548   geckodriver     INFO    Listening on 127.0.0.1:45880
1529337489042   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\cmartin\\AppData\\Local\\Temp\\rust_mozprofile.S75ou56mcl1r"
Unable to read VR Path Registry from C:\Users\cmartin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\cmartin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\cmartin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\cmartin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\cmartin\AppData\Local\openvr\openvrpaths.vrpath
1529337490525   Marionette      INFO    Listening on port 61812
17:58:10.697 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@73cfd8e
17:58:10.698 INFO - Handler thread for session f3227460-78e7-4847-a8ef-2855a3e555e4 (firefox): Executing POST on /session/f3227460-78e7-4847-a8ef-2855a3e555e4/url (handler: ServicedSession)
17:58:13.547 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@73cfd8e
17:58:13.547 INFO - Handler thread for session f3227460-78e7-4847-a8ef-2855a3e555e4 (firefox): Executing POST on /session/f3227460-78e7-4847-a8ef-2855a3e555e4/elements (handler: ServicedSession)
17:58:13.572 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@73cfd8e
17:58:13.572 INFO - Handler thread for session f3227460-78e7-4847-a8ef-2855a3e555e4 (firefox): Executing POST on /session/f3227460-78e7-4847-a8ef-2855a3e555e4/elements (handler: ServicedSession)
17:58:13.584 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@73cfd8e
17:58:13.584 INFO - Handler thread for session f3227460-78e7-4847-a8ef-2855a3e555e4 (firefox): Executing GET on /session/f3227460-78e7-4847-a8ef-2855a3e555e4/screenshot (handler: ServicedSession)
17:58:13.699 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@73cfd8e
17:58:13.699 INFO - Handler thread for session f3227460-78e7-4847-a8ef-2855a3e555e4 (firefox): Executing DELETE on /session/f3227460-78e7-4847-a8ef-2855a3e555e4 (handler: ServicedSession)
[Parent 17872, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 7732, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 7732, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ip[Child 15572, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 15572, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 17872, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 12656, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 12656, Chrome_ChildThread] WARNING: pipe error: 1*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
[GPU 9352, Chrome_ChildThread] WARNING: pipe error:
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

17:58:14.328 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@73cfd8e

**Comment by whimboo** [comment]
For everyone experiencing this problem can you please check if there is a minidump report present for Firefox? As it looks like the tab is crashing, or the inter-process communication is busted. 

https://firefox-source-docs.mozilla.org/testing/geckodriver/doc/geckodriver/CrashReports.html

**Comment by HristoTest** [comment]
I found a minidump folder, but without any files.

**Comment by tapioreijonen** [comment]
Tools ; selenium standalone server : 3.12.0 / geckodriver: 0.21.0 (win64) / firefox 60.0.2
None dump files created.

Using geckodriver: 0.20.1 same tests works without any problems

[geckodriver.log](https://github.com/mozilla/geckodriver/files/2114725/geckodriver.log)

**Comment by whimboo** [comment]
@thomhurst, you as original reporter would you mind to supply a trace log as requested in comment https://github.com/mozilla/geckodriver/issues/1216#issuecomment-374625435 on March 20th? Thanks.

**Comment by whimboo** [comment]
@tapioreijonen your log shows quiet a bit of add-on manager related log output. Mind telling me if something in your tests is setting the Firefox preference `extensions.logging.enabled` to `true`? Which binding are you using btw?

Otherwise could everyone test again with Firefox 61.0 which we released this week, or even better with a currently Nightly build which can be found here: https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

Thanks.

**Comment by Sondt88** [comment]
@whimboo I have checked with Firefox 61 and the issue is still here.

 Element not found with xpath, //html
       (WebDriver\Exception\NoSuchElement)
    │
    ╳  Element not found with xpath, //html
    ╳   (WebDriver\Exception\NoSuchElement)

Could you please help me to troubleshoot this ?

**Comment by deckcha** [comment]
How to fix this issues

1532077768082	geckodriver	INFO	geckodriver 0.21.0
1532077768090	geckodriver	INFO	Listening on 127.0.0.1:27207
1532077768755	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Tannay\\AppData\\Local\\Temp\\rust_mozprofile.LhR0ZEYDdMlf"
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1532077770384	Marionette	INFO	Listening on port 2828
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
Exception in thread "main" org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 0
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'DESKTOP-40OK0AG', ip: '192.168.1.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at pack.FaceBook.main(FaceBook.java:14)

**Comment by whimboo** [comment]
@Sondt88 not without a trace log. Check the comments above in how to retrieve and attach one.

**Comment by Sondt88** [comment]
@whimboo Hello Whimboo,

I ran command line : geckodriver -vv

It only shows these information : 
1532488621646   geckodriver     INFO    geckodriver 0.21.0
1532488621647   webdriver::httpapi      DEBUG   Creating routes
1532488621652   geckodriver     INFO    Listening on 127.0.0.1:4444

Please correct me if something goes wrong.

**Comment by whimboo** [comment]
@Sondt88 well you will have to run your test to create the tracelog. Just starting geckodriver won't help here.

**Comment by Sondt88** [comment]
@whimboo ahh, sorry. I have kicked off the test and trace log only shows information above.

Here are my full steps : 
1. Start gecko driver with selenium : java -jar -Dwebdriver.gecko.driver="geckodriver" "selenium-server-standalone-3.13.0.jar"
2. Run command line : geckodriver -vv
3. Kick off my test : vendor/bin/behat

After that : 
- Behat shows error : 
Element not found with xpath, //html
(WebDriver\Exception\NoSuchElement)

- Trace log only shows : 
1532488621646 geckodriver INFO geckodriver 0.21.0
1532488621647 webdriver::httpapi DEBUG Creating routes
1532488621652 geckodriver INFO Listening on 127.0.0.1:4444

Please review my step if I have any mistake there.

Thanks so much.

**Comment by andreastt** [comment]
See https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md on how to enable trace logs. There are examples near the bottom.

**Comment by Sondt88** [comment]
@andreastt : yes, I tried with some commands 
- geckodriver -vv
- geckodriver --log trace

But it still only displays 
1532488621646 geckodriver INFO geckodriver 0.21.0
1532488621647 webdriver::httpapi DEBUG Creating routes
1532488621652 geckodriver INFO Listening on 127.0.0.1:4444

**Comment by andreastt** [comment]
Right, and then you need to run your test.

**Comment by Sondt88** [comment]
@andreastt yes, I did but it still only shows :(

1532488621646 geckodriver INFO geckodriver 0.21.0
1532488621647 webdriver::httpapi DEBUG Creating routes
1532488621652 geckodriver INFO Listening on 127.0.0.1:4444

**Comment by andreastt** [comment]
This is a waste of our time.

You need to provide a trace-level log from the geckodriver used in your test that showcases the original problem you described. If you just run `geckodriver -vv` from the command-line, you need to instruct your Selenium client to hit that server instead of the server it automatically spawns.

I will consider re-opening this if the appropriate information is added to reproduce this issue.

**Comment by Sondt88** [comment]
@andreastt : Sorry if it takes your time.
I am a new member so that I need sometime to research before using.
I will try again and provide more information at this weekend.

Thank you and sorry for any inconvenience.

**Comment by parshudhole** [comment]
Any update on this issue ? We are blocked on our automation for Firefox.
