### ISSUE TITLE
geckodriver 0.31.0 release is no longer available for download

### ISSUE THREAD

**Issue by kingthorin** [mozilla/geckodriver#2009]
This is a repo issue:
https://api.github.com/repos/mozilla/geckodriver/releases/latest seems to point to [0.30.0](https://github.com/mozilla/geckodriver/releases/tag/v0.30.0) (not [0.31.0](https://github.com/mozilla/geckodriver/releases/tag/v0.31.0)) for some reason.

I was in the process of setting up some automation when I noticed this discrepancy.

Could you correct this one-off and tweak your release process to ensure that "latest" is properly pointed/updated?

**Comment by whimboo** [comment]
Thanks for notifying us! Strangely the 0.31.0 release was even completely gone from the https://github.com/mozilla/geckodriver/releases page. Not sure what's going on with Github at this point but this seems concerning. A no-op edit of the release page brought it actually back.

Now latest points again to 0.31.0.

**Comment by kingthorin** [comment]
Thanks!

**Comment by kingthorin** [comment]
I think you need to hit up someone from GitHub because this seems to have broken again.

**Comment by kingthorin** [comment]
Ummmm actually the whole 0.31.0 release seem gone?
![image](https://user-images.githubusercontent.com/7570458/166848268-128975c2-4a00-486e-9e5d-5b9102dd824d.png)

Though the tag still exists:
![image](https://user-images.githubusercontent.com/7570458/166848334-4308ce29-4e9e-4d8b-8a1e-db0ba0105e96.png)

**Comment by whimboo** [comment]
Yes, there is nothing that I'll do this time. I'm going to leave the repository in this state and hope that GitHub support can fix the underlying issue for real. As they reported it was an issue only affecting some customers and that this should have been fixed, but it's not the case. Note that there is no public announcement as well on their side for this particular issue. :/

**Comment by mariotrucco** [comment]
> Yes, there is nothing that I'll do this time. I'm going to leave the repository in this state and hope that GitHub support can fix the underlying issue for real. As they reported it was an issue only affecting some customers and that this should have been fixed, but it's not the case. Note that there is no public announcement as well on their side for this particular issue. :/

FYI, at the time of this writing Friday, 6 May 2022 09:58 UTC, https://github.com/mozilla/geckodriver/releases correctly shows `0.31.0` as latest and our automations are fixed

**Comment by mariotrucco** [comment]
And now the error is back. https://github.com/mozilla/geckodriver/releases Currently says that latest is 0.29.1

**Comment by mariotrucco** [comment]
And now the error is back. https://github.com/mozilla/geckodriver/releases Currently says that latest is 0.29.1

**Comment by whimboo** [comment]
I quickly patched so that at least our latest security release 0.30.0 is listed as latest. I'll poke GitHub support again given that it's becoming kinda annoying now. Thanks for letting us know!

**Comment by whimboo** [comment]
Via GitHub support this should be fixed since late Friday. Given that so far it still shows version 0.31.0 I assume it's true. Lets close this issue.

Thanks everyone for giving us feedback that quickly.
