### ISSUE TITLE
Unable to click button under some other element

### ISSUE THREAD

**Issue by harshg0910** [mozilla/geckodriver#243]
Geckodriver Version : 0.10.0
Selenium : 3.0.0beta 3
Firefox : 48.0.2
In selenium implementation of firefox webdriver, it used to give 'Other element would receive the click' exception when it tries to click element under some other element.
But when I'm using geckodriver, it is silently clicking at the position leading to coverer getting clicked without any error.
Is this behavior intended ? Similar discussion happened here
https://github.com/seleniumhq/selenium/issues/1202
and 
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5142

**Comment by andreastt** [comment]
It’s not the intention for this _not_ to throw. What is happening in geckodriver, is the element getting clicked?

Can you try to run your test again, with setting the capability `specificationLevel` to `1`? This will trigger some other element interactability checks.

**Comment by harshg0910** [comment]
Click is getting triggered but element who is covering actual button is getting clicked.

In Selenium's webdriver, I think they try to scroll element into view using JS and then perform a click.
If not possible, it throws exceptions that other element would be clicked.

Nothing changed with specificationLevel.

**Comment by andreastt** [comment]
Okay, thanks for the feedback. Can you provide a reproducible and minimal test case?

**Comment by harshg0910** [comment]
HTML code is attached in 
[coveredButton.txt](https://github.com/mozilla/geckodriver/files/502871/coveredButton.txt)
(could not upload .html hence attaching .txt )

       public void click_button()
        {
            IWebDriver driver = new FirefoxDriver(new FirefoxOptions());
            driver.Navigate().GoToUrl("coveredButton.html");
            By by = By.XPath("/html/body/button");
            var button = driver.FindElement(by);
            button.Click();
        }

When this button is clicked I get an alert saying "Coverer Clicked" but my intention was to click button

Geckodriver Version : 0.10.0
Selenium : 3.0.0beta 3
Firefox : 48.0.2

**Comment by crazcalm** [comment]
I am also having a problem clicking on elements.

I found a [stack overflow post](http://stackoverflow.com/questions/40080077/selenium-3-firefox-click-not-working) that might bring more clarity to the problem. As far as I know, there is no work around for this.

Thanks in advance for looking into this issue!

**Comment by andreastt** [comment]
@harshg0910 

I rewrote large portions of the WebDriver conformant pointer interactability algorithm in [bug 1317386](https://bugzilla.mozilla.org/show_bug.cgi?id=1317386). This is currently hidden behind the `specificationLevel` capability.

Can you run your test code again on a fresh [Firefox Nightly](https://nightly.mozilla.org/) with `{"specificationLevel": 1}` set as a desired capability?

**Comment by andreastt** [comment]
@harshg0910 Still waiting on your feedback. Can you please run your test again with {"specificationLevel": 1}` set as a capability in a recent [Firefox Nightly](https://nightly.mozilla.org/)? This will trigger the WebDriver conforming element interactability implementation, which should be more accurate than Selenium’s.

**Comment by Galad** [comment]
Hello,
Having the same issue, I tried to run a nightly build with the the capability but it doesn't work better. I ran the same test as the OP.
Here is how I created the driver and added the capability :

    var options = new FirefoxOptions();            
    options.AddAdditionalCapability("specificationLevel", 1);            
    options.BrowserExecutableLocation = @"C:\Program Files\Nightly\firefox.exe";            
    var driver = new FirefoxDriver(options);          `

Firefox : 53.0a1 (2017-01-19) (64-bit)
Selenium : 3.0.1
Firefox driver : 0.13.0

**Comment by andreastt** [comment]
@Galad Can you conjure up a reproducible test case? A minimal HTML document would be helpful.

**Comment by Galad** [comment]
@andreastt Sure

Here is the HTML file I'm using : https://gist.github.com/Galad/dfed9764bd1381efa1ee9c997aed7871
And here is the complete unit test (in C# with xunit) 

    public class TestClick
    {
    	[Fact]
    	public void TestClickOnInaccessibleElement()
    	{
    		var options = new FirefoxOptions();
    		options.AddAdditionalCapability("specificationLevel", 1);
    		options.BrowserExecutableLocation = @"C:\Program Files\Nightly\firefox.exe";
    		using (var driver = new FirefoxDriver(options))
    		{                
    			var url = "http://localhost:52765/TestClick.html";
    			driver.Navigate().GoToUrl(url);
    			var link = driver.FindElement(By.Id("ElementClick"));
    			Assert.ThrowsAny<Exception>(() => link.Click());
    		}
    	}
    }

The behavior is that the Overlay element takes the click ("overlay" is written in the console), but no error is thrown.

**Comment by andreastt** [comment]
@Galad With `specificationLevel` set to 1, it returns an ‘element not visible’ error on that HTML document you attached. Because the element is obscured by the overlay, a click would not bubble down to it, and this is expected behaviour.

The WebDriver specification very recently changed to say that we should return an ‘element click intercepted’ error when another element is obscuring the targetted element, however, and Marionette is not returning this error yet.

**Comment by zzhengjian** [comment]
So with specificationLevel set to 1, would the returned value of isdisplayed for the element being overlayed be false now?

**Comment by andreastt** [comment]
Today I pushed https://bugzilla.mozilla.org/show_bug.cgi?id=1333014 to central. Once it lands in Nightly, you should try _once again_ with `specificationLevel` set to 1, if you wouldn’t mind.

**Comment by andreastt** [comment]
@zzhengjian The expected WebDriver behaviour is for a click on an element that is obscured by another (the targetted element has a lower paint order than the element positioned on top of it), is for it to return an ‘element not interactable’ error.

**Comment by andreastt** [comment]
@harshg0910 See my earlier comment, https://github.com/mozilla/geckodriver/issues/243#issuecomment-288578227. Can you try once again with the latest [Nightly](https://nightly.mozilla.org/) and `specificationLevel` to set to 1?

Could you also attach a minimal HTML document showcasing the problem?

**Comment by andreastt** [comment]
Closing this issue because of inactivity. Happy to re-open if you think this is still an issue.

**Comment by aliaksandrbasau** [comment]
@andreastt I still see the issue. Can we please resume working on it? I can help you to reproduce it and to test the fixes. You can also count on prompt responses from me.

I tried to set specificationLevel to 1 but FirefoxDriver throws an exception - "specificationLevel was not a the name of a known capability or a valid extension capability". I tried Nightly and Release builds but no luck. Here is my C# code. Please let me know if specificationLevel has to be set differently.

```
var options = new FirefoxOptions()
{
	LogLevel = FirefoxDriverLogLevel.Trace,
	BrowserExecutableLocation = @"c:\Program Files\Nightly\firefox.exe"
};

options.AddAdditionalCapability("specificationLevel", "1");

using (var driver = new FirefoxDriver(options))
{
}
```

WebDriver: 3.6.0
Geckodriver: 0.19.0
Language: C#
Firefox: 56.0.1 (64-bit), 58.0a1 (2017-10-12) (64-bit)

Here is C# solution to reproduce the issue
[GeckoClick.zip](https://github.com/mozilla/geckodriver/files/1380095/GeckoClick.zip)

**Comment by aliaksandrbasau** [comment]
@andreastt Just found https://bugzilla.mozilla.org/show_bug.cgi?id=1387470 and tested in Firefox 57 with
`options.AddAdditionalCapability("moz:webdriverClick", true, true);`
My issue looks resolved - web driver throws an exception if the element that is covered by other element is clicked.

**Comment by andreastt** [comment]
@aliaksandrbasau I was about to mention that it since got exposed on geckodriver as `moz:webdriverClick`, so it is excellent that you found that yourself and tested. I’m glad to hear your issues were resolved.

Enabling this behaviour by default is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1321516, which we should hopefully be able to do soon.

**Comment by aliaksandrbasau** [comment]
@andreastt Many thanks for fixing the issue! It was the last one that stopped from migrating to Gecko driver. Hopefully we will be able to migrate after Firefox 57 is release on 2017-11-14.
