### ISSUE TITLE
Unable to properly .Click() a found, but hidden <li> element in pseudo-dropdowns

### ISSUE THREAD

**Issue by redwards510** [mozilla/geckodriver#324]
This problem began when I switched from ChromeDriver to GeckoDriver 0.11.1. It would help for me to use an image to explain the problem:
![geckodriver_bug](https://cloud.githubusercontent.com/assets/8303176/20082213/3baf7270-a509-11e6-878c-e06e338bfe20.png)

The basic code I use to open the drop down, then select the item is below. WaitUntilElementStopsMoving(By by) is a bit long to paste here. All it does it check the location.X/Y of an element to make sure it hasnt moved in 100ms. 

           //(1) click the drop down to pop it open and display the items
            WaitForElementToBeClickableThenClick(By.XPath("//span[contains(text(), 'Select court...')]/following::span/span"));
           //(2) select the desired item from the displayed list
            WaitForElementToBeClickableThenClick(By.XPath($"//ul[@id='court_listbox']/li[contains(text(), '{court}')]"));

        private void WaitForElementToBeClickableThenClick(By by)
        {
            WaitUntilElementStopsMoving(by);
            _wait.Until(ExpectedConditions.ElementToBeClickable(by));
            Host.Browser.FindElement(by).Click();
        }

Why it's a bug, not user error:
a) it works in ChromeDriver as-is. 
b) it works when the desired drop down element I want selected is *visible* upon the initial pop open. It's only when I want an element that is farther down the list that it fails to properly click. Usually when you use .Click() it auto-scrolls to the element desired.

Other notes: 
* The weird part is it is doing *something*. Because when it performs the faulty .Click() in step (2), the drop down list closes. It just doesn't select anything. 
* I can't do a workaround of using Javascript Executor to select the item. There's validation junk going on when you click on the drop down. 
* Would a scrollTo work in this case?
Source of the <ul> code from KendoUI (sorry it's a pic)
![geckodriver_bug_source](https://cloud.githubusercontent.com/assets/8303176/20082422/8b546244-a50a-11e6-906f-22c71e6aaf21.png)

**Comment by redwards510** [comment]
I tried to create a JSfiddle to demonstrate this, but I'm running up against another bug where it won't even click the drop down list on a js-intensive site. Here's the fiddle: http://jsfiddle.net/redwards510/pdhhj47b/3/
```

        [Test]
        public void SampleTest()
        {            
            Host.Browser.Navigate().GoToUrl("http://jsfiddle.net/redwards510/pdhhj47b/2/");            
            // open drop down
            Host.Browser.FindElement(By.XPath("//span[contains(text(), 'List Option 1')]/following::span/span")).Click();            
            // wait for drop down to open
            Thread.Sleep(1000);
            // try to select an element which is in the lsit but hidden from view without scrolling
            // note it isnt a real drop down <select> element. It's KendoUI.
            Host.Browser.FindElement(By.XPath($"//ul[@id='dropdownlist_listbox']/li[contains(text(), 'HIDDEN List Option 11')]")).Click();            
        }
```

**Comment by danhumphrey** [comment]
I'm glad you could provide a small reproducible fiddle for this - I've encountered a number of issues where click fails to work with GeckoDriver and Selenium 3, but I haven't been able to extract a public test case. 

FWIW I have various examples which:

* Work in all browsers (including FF) using Selenium 2.53
* Work in Edge and Chrome using Selenium 3.0.1
* Do not work with FF Nightly or 49.*.* with Selenium 3.0.1

The element is found and there are no exceptions thrown.

**Comment by danhumphrey** [comment]
I think you are missing `switchTo().frame(0) ` to get your demo working.

The following Java snippet demonstrates the issue regarding the hidden option (li):

```java
public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.gecko.driver",System.getenv("FIREFOX_DRIVER"));
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		
		WebDriver driver = new FirefoxDriver(capabilities);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.get("http://fiddle.jshell.net/redwards510/pdhhj47b/2/show/");            
        // open drop down
		driver.switchTo().frame(0);
        driver.findElement(By.className("k-i-arrow-s")).click();            
        // wait for drop down to open
        Thread.sleep(1000);
        // try to select an element which is in the lsit but hidden from view without scrolling
        // note it isnt a real drop down <select> element. It's KendoUI.
        driver.findElement(By.xpath("//ul[@id='dropdownlist_listbox']/li[contains(text(), 'List Option 3')]")).click(); //this is visible and DOES get clicked
        driver.findElement(By.xpath("//ul[@id='dropdownlist_listbox']/li[contains(text(), 'HIDDEN List Option 11')]")).click(); // this is NOT visible and DOES NOT get clicked
        
	}
```

**Comment by redwards510** [comment]
Thanks @danhumphrey ! The test case does now work to demonstrate the issue. I've updated my code.

**Comment by andreastt** [comment]
You didn’t say which Firefox version you are running this against. Support for interacting with `<select>` elements was added in [bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955). Can you try again with a fresh [Firefox Nightly](https://nightly.mozilla.org/)?

**Comment by andreastt** [comment]
As we’re unable to reproduce this, I’m closing it. If you disagree, I’m happy to reopen once sufficient information to reproduce the issue has been added.

**Comment by dmitryyu** [comment]
The issue is still reproduced for FF 57.0.2 with geckdriver 0.19 and wd lib 3.7.0
`
public class ScrollFF {

	@FindBy(id = "uxiframe-1061-iframeEl")
	private WebElement iframe;

	@FindBy(id = "combobox-1009-inputEl")
	private WebElement input;

	@FindBy(id ="combobox-1009-trigger-picker")
	private WebElement trigger;

	@FindBy (css = "li[data-recordindex='1']")
	private WebElement option1;

	@FindBy (css = "li[data-recordindex='13']")
	private WebElement option13;


	@Test
	public void testCustomDropDown() throws InterruptedException {
		WebDriver driver = new FirefoxDriver();
		PageFactory.initElements(driver, this);
		driver.get("https://fiddle.sencha.com/#view/editor&fiddle/2aq0");
		Thread.sleep(5000);
		driver.switchTo().frame(iframe);

		waitForElementToBeClickable(driver, trigger);
		trigger.click();
		waitForElementToBeClickable(driver, option1);
		option1.click();
		Assert.assertEquals(input.getAttribute("value"), "Alaska1", "Visible option is not selected");

		trigger.click();
		waitForElementToBeClickable(driver, option13);
		option13.click();
		Assert.assertEquals(input.getAttribute("value"), "Alaska13", "Not visible option  Element is not selected");
	}


	private void waitForElementToBeClickable(WebDriver driver, WebElement element) {
		new WebDriverWait(driver, 10000, 1000).until(
				ExpectedConditions.elementToBeClickable(element)
		);
	}
`

**Comment by whimboo** [comment]
@dmitryyu why do you think your issue is the same? Please file your problem as a new issue with all the details as requested. Thanks.
