### ISSUE TITLE
driver.navigate().back() does not return until timeout while using Turbolinks

### ISSUE THREAD

**Issue by KSKS** [mozilla/geckodriver#697]
## Firefox Version
Firefox version: 53.0

## Platform
OSX, reproduced on Windows

## Other
selenium-webdriver v3.4.0
geckodriver v0.16.0

## Steps to reproduce -
1. Use webdriver to start firefox, go visit a page that uses turbolinks (a.html)
2. click a link to visit another page (b.html)
3. call driver.navigate().back() to return to the first page

Expected: Firefox returns to the first page
Actual: The back request never return, until error in timeout.

Please provide a description of how to reproduce the problem:
all files provided in [issue_files.zip](https://github.com/mozilla/geckodriver/files/962125/issue_files.zip)
Host a server that serve the provided a.html, b.html and turbolinks.js from localhost:3001
In folder node_selenium:
run "npm install"
place geckodriver in your PATH
run "node index.js"

Note:
1. Although the html files can be served on their own, I originally discover this issue while testing against a Rails website, which uses Turbolinks by default.
2. Going back in history using Turbolinks would not trigger a new network request, instead it would render the page from cache (and changes the history, etc). See more at [here from Turbolinks](https://github.com/turbolinks/turbolinks#restoration-visits)

Log snippet:
1493306478210	webdriver::server	DEBUG	→ POST /session/0025e2e4-f778-334a-8b4b-77f7bbd9c298/back {}
1493306478210	geckodriver::marionette	TRACE	→ 17:[0,5,"goBack",{}]
1493306478212	Marionette	TRACE	conn0 -> [0,5,"goBack",{}]
1493306778219	Marionette	TRACE	conn0 <- [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nTimeoutError@chrome://marionette/content/error.js:430:5\nnotify@chrome://marionette/content/listener.js:227:15\n"},null]

**Comment by whimboo** [comment]
@KSKS can you please use the latest Firefox Nightly, run the tests again, and provide a full trace log? Thanks.

**Comment by KSKS** [comment]
log with nightly

> 1493913038577	webdriver::httpapi	DEBUG	Creating routes
> 1493913038587	geckodriver	INFO	Listening on 127.0.0.1:4444
> 1493913038657	webdriver::server	DEBUG	→ GET /status
> 1493913038659	webdriver::server	DEBUG	← 200 OK {"value":{"message":"","ready":true}}
> 1493913038682	webdriver::server	DEBUG	→ POST /session {"desiredCapabilities":{"browserName":"firefox","nativeEvents":true,"marionette":true,"moz:firefoxOptions":{"binary":"/Applications/FirefoxNightly.app/Contents/MacOS/firefox"}}}
> 1493913039737	geckodriver::marionette	INFO	Starting browser /Applications/FirefoxNightly.app/Contents/MacOS/firefox with args ["-marionette"]
> 1493913039741	geckodriver::marionette	TRACE	  connection attempt 0/600
> 1493913039843	geckodriver::marionette	TRACE	  connection attempt 1/600
> 1493913039944	geckodriver::marionette	TRACE	  connection attempt 2/600
> 1493913040047	geckodriver::marionette	TRACE	  connection attempt 3/600
> 1493913040149	geckodriver::marionette	TRACE	  connection attempt 4/600
> 1493913040255	geckodriver::marionette	TRACE	  connection attempt 5/600
> 1493913040360	geckodriver::marionette	TRACE	  connection attempt 6/600
> 1493913040465	geckodriver::marionette	TRACE	  connection attempt 7/600
> 1493913040571	geckodriver::marionette	TRACE	  connection attempt 8/600
> 1493913040675	geckodriver::marionette	TRACE	  connection attempt 9/600
> 1493913040781	geckodriver::marionette	TRACE	  connection attempt 10/600
> 1493913040883	geckodriver::marionette	TRACE	  connection attempt 11/600
> 1493913040985	geckodriver::marionette	TRACE	  connection attempt 12/600
> 1493913041088	geckodriver::marionette	TRACE	  connection attempt 13/600
> 1493913041194	geckodriver::marionette	TRACE	  connection attempt 14/600
> 1493913041298	geckodriver::marionette	TRACE	  connection attempt 15/600
> 1493913041401	geckodriver::marionette	TRACE	  connection attempt 16/600
> 1493913041503	geckodriver::marionette	TRACE	  connection attempt 17/600
> 1493913041608	geckodriver::marionette	TRACE	  connection attempt 18/600
> 1493913041710	geckodriver::marionette	TRACE	  connection attempt 19/600
> 1493913041814	geckodriver::marionette	TRACE	  connection attempt 20/600
> 1493913041920	geckodriver::marionette	TRACE	  connection attempt 21/600
> 1493913042025	geckodriver::marionette	TRACE	  connection attempt 22/600
> 1493913042127	geckodriver::marionette	TRACE	  connection attempt 23/600
> 1493913042229	geckodriver::marionette	TRACE	  connection attempt 24/600
> 1493913042334	geckodriver::marionette	TRACE	  connection attempt 25/600
> 1493913042439	geckodriver::marionette	TRACE	  connection attempt 26/600
> 1493913042543	geckodriver::marionette	TRACE	  connection attempt 27/600
> 1493913042646	geckodriver::marionette	TRACE	  connection attempt 28/600
> 1493913042752	geckodriver::marionette	TRACE	  connection attempt 29/600
> 1493913042857	geckodriver::marionette	TRACE	  connection attempt 30/600
> 1493913042959	geckodriver::marionette	TRACE	  connection attempt 31/600
> 1493913043064	geckodriver::marionette	TRACE	  connection attempt 32/600
> 1493913043167	geckodriver::marionette	TRACE	  connection attempt 33/600
> 1493913043273	geckodriver::marionette	TRACE	  connection attempt 34/600
> 1493913043354	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
> 1493913043355	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
> 1493913043356	Marionette	INFO	Listening on port 53471
> 1493913043378	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:53471
> 1493913043424	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:53581
> 1493913043450	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
> 1493913043450	geckodriver::marionette	TRACE	→ 185:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},"marionette":true,"nativeEvents":true}]
> 1493913043468	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},"marionette":true,"nativeEvents":true}]
> 1493913043477	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12619,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.jYuclCfa1t2o","moz:accessibilityChecks":false}
> 1493913043773	Marionette	DEBUG	loaded listener.js
> 1493913043828	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"d9d7cc0a-0878-264f-8115-537715aec6d6","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12619,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.jYuclCfa1t2o","moz:accessibilityChecks":false}}]
> 1493913043841	geckodriver::marionette	TRACE	← [1,1,null,{"sessionId":"d9d7cc0a-0878-264f-8115-537715aec6d6","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":12619,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.jYuclCfa1t2o","moz:accessibilityChecks":false}}]
> 1493913043845	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"d9d7cc0a-0878-264f-8115-537715aec6d6","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":12619,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.jYuclCfa1t2o","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"15.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
> 1493913043875	webdriver::server	DEBUG	→ POST /session/d9d7cc0a-0878-264f-8115-537715aec6d6/url {"url":"http://localhost:3001/a"}
> 1493913043879	geckodriver::marionette	TRACE	→ 45:[0,2,"get",{"url":"http://localhost:3001/a"}]
> 1493913043884	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://localhost:3001/a"}]
> 1493913043949	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
> 2017-05-04 08:50:44.047 plugin-container[12621:292500] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d3f, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2017-05-04 08:50:44.053 plugin-container[12621:292500] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x5207, name = 'com.apple.CFPasteboardClient'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2017-05-04 08:50:44.054 plugin-container[12621:292500] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
> 1493913044080	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
> 1493913044081	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
> 2017-05-04 08:50:44.152 plugin-container[12622:292544] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x993f, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2017-05-04 08:50:44.153 plugin-container[12622:292544] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x4e37, name = 'com.apple.CFPasteboardClient'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2017-05-04 08:50:44.153 plugin-container[12622:292544] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
> 1493913044244	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:3001/a"
> 1493913044256	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:3001/a"
> 1493913044267	Marionette	TRACE	0 <- [1,2,null,{}]
> 1493913044292	geckodriver::marionette	TRACE	← [1,2,null,{}]
> 1493913044292	webdriver::server	DEBUG	← 200 OK {"value": {}}
> 1493913045309	webdriver::server	DEBUG	→ POST /session/d9d7cc0a-0878-264f-8115-537715aec6d6/elements {"using":"css selector","value":"html > body > a"}
> 1493913045310	geckodriver::marionette	TRACE	→ 71:[0,3,"findElements",{"using":"css selector","value":"html > body > a"}]
> 1493913045312	Marionette	TRACE	0 -> [0,3,"findElements",{"using":"css selector","value":"html > body > a"}]
> 1493913045322	Marionette	TRACE	0 <- [1,3,null,[{"element-6066-11e4-a52e-4f735466cecf":"fae46a94-0197-484c-b32a-49d000c54b39","ELEMENT":"fae46a94-0197-484c-b32a-49d000c54b39"}]]
> 1493913045323	geckodriver::marionette	TRACE	← [1,3,null,[{"element-6066-11e4-a52e-4f735466cecf":"fae46a94-0197-484c-b32a-49d000c54b39","ELEMENT":"fae46a94-0197-484c-b32a-49d000c54b39"}]]
> 1493913045324	webdriver::server	DEBUG	← 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"fae46a94-0197-484c-b32a-49d000c54b39"}]}
> 1493913045329	webdriver::server	DEBUG	→ POST /session/d9d7cc0a-0878-264f-8115-537715aec6d6/element/fae46a94-0197-484c-b32a-49d000c54b39/click {}
> 1493913045330	geckodriver::marionette	TRACE	→ 66:[0,4,"clickElement",{"id":"fae46a94-0197-484c-b32a-49d000c54b39"}]
> 1493913045331	Marionette	TRACE	0 -> [0,4,"clickElement",{"id":"fae46a94-0197-484c-b32a-49d000c54b39"}]
> 1493913045682	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
> 1493913045684	Marionette	TRACE	0 <- [1,4,null,{}]
> 1493913045685	geckodriver::marionette	TRACE	← [1,4,null,{}]
> 1493913045685	webdriver::server	DEBUG	← 200 OK {"value": {}}
> navigate back
> 1493913046692	webdriver::server	DEBUG	→ POST /session/d9d7cc0a-0878-264f-8115-537715aec6d6/back {}
> 1493913046693	geckodriver::marionette	TRACE	→ 17:[0,5,"goBack",{}]
> 1493913046695	Marionette	TRACE	0 -> [0,5,"goBack",{}]
> 1493913346707	Marionette	TRACE	0 <- [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:212:5\nTimeoutError@chrome://marionette/content/error.js:455:5\nnotify@chrome://marionette/content/listener.js:298:17\n"},null]
> 1493913346709	geckodriver::marionette	TRACE	← [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:212:5\nTimeoutError@chrome://marionette/content/error.js:455:5\nnotify@chrome://marionette/content/listener.js:298:17\n"},null]
> 1493913346728	webdriver::server	DEBUG	← 408 Request Timeout {"value":{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"stack backtrace:\n   0:        0x10261a37e - backtrace::backtrace::trace::h76b688ec9dd0c4e2\n   1:        0x10261aabc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:        0x1025cdeaf - webdriver::error::WebDriverError::new::h6e7bc24f03499973\n   3:        0x1025de7cb - geckodriver::marionette::MarionetteSession::response::h06a886e7e8d17c71\n   4:        0x1025dc663 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::h1551b734f4cde0a0\n   5:        0x1025ce340 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::h89f46c6cb17a6c48\n   6:        0x1025a1dcd - std::panicking::try::do_call::h20be620158d9b55a\n   7:        0x1027445ba - __rust_maybe_catch_panic\n   8:        0x1025b0aea - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h4fac0ee9906c8727\n   9:        0x102742a14 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f\n  10:     0x7fffa038699c - _pthread_body\n  11:     0x7fffa0386919 - _pthread_start"}}
> Error: TimeoutError: Timeout loading page after 300000ms
> 1493913346735	webdriver::server	DEBUG	→ DELETE /session/d9d7cc0a-0878-264f-8115-537715aec6d6
> 1493913346735	geckodriver::marionette	TRACE	→ 48:[0,6,"quitApplication",{"flags":["eForceQuit"]}]
> 1493913346739	Marionette	TRACE	0 -> [0,6,"quitApplication",{"flags":["eForceQuit"]}]
> 1493913346744	Marionette	INFO	New connections will no longer be accepted
> 1493913346849	Marionette	TRACE	0 <- [1,6,null,{"cause":"shutdown"}]
> 1493913346884	geckodriver::marionette	TRACE	← [1,6,null,{"cause":"shutdown"}]
> 1493913346885	webdriver::server	DEBUG	Deleting session
> 1493913346885	geckodriver::marionette	DEBUG	Stopping browser process
> ** Unknown exception behavior: -2147483647
> ** Unknown exception behavior: -2147483647
> 1493913346964	webdriver::server	DEBUG	← 200 OK {"value": {}}

**Comment by AutomatedTester** [comment]
@whimboo details requested have been added

**Comment by whimboo** [comment]
The problem here seems to be with:

> 1493913045331	Marionette	TRACE	0 -> [0,4,"clickElement",{"id":"fae46a94-0197-484c-b32a-49d000c54b39"}]
> 1493913045682	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
> 1493913045684	Marionette	TRACE	0 <- [1,4,null,{}]

That was a bug which has already been fixed in Nightly. Because we didn't wait long enough here, the invocation of ´goBack´ runs into a timeout due to no page in the bfcache.

@KSKS please test again by using the latest nightly.

**Comment by KSKS** [comment]
Same result with Nightly 55.0a1 (2017-05-11)
```

1494602675817	webdriver::httpapi	DEBUG	Creating routes
1494602675822	geckodriver	INFO	Listening on 127.0.0.1:4444
1494602675839	webdriver::server	DEBUG	→ GET /status
1494602675840	webdriver::server	DEBUG	← 200 OK {"value":{"message":"","ready":true}}
1494602675867	webdriver::server	DEBUG	→ POST /session {"desiredCapabilities":{"browserName":"firefox","nativeEvents":true,"marionette":true,"moz:firefoxOptions":{"binary":"/Applications/FirefoxNightly.app/Contents/MacOS/firefox"}}}
1494602676437	geckodriver::marionette	INFO	Starting browser /Applications/FirefoxNightly.app/Contents/MacOS/firefox with args ["-marionette"]
1494602676893	geckodriver::marionette	TRACE	  connection attempt 0/600
1494602676997	geckodriver::marionette	TRACE	  connection attempt 1/600
1494602677100	geckodriver::marionette	TRACE	  connection attempt 2/600
1494602677204	geckodriver::marionette	TRACE	  connection attempt 3/600
1494602677309	geckodriver::marionette	TRACE	  connection attempt 4/600
1494602677413	geckodriver::marionette	TRACE	  connection attempt 5/600
1494602677516	geckodriver::marionette	TRACE	  connection attempt 6/600
1494602677622	geckodriver::marionette	TRACE	  connection attempt 7/600
1494602677725	geckodriver::marionette	TRACE	  connection attempt 8/600
1494602677831	geckodriver::marionette	TRACE	  connection attempt 9/600
1494602677936	geckodriver::marionette	TRACE	  connection attempt 10/600
1494602678037	geckodriver::marionette	TRACE	  connection attempt 11/600
1494602678143	geckodriver::marionette	TRACE	  connection attempt 12/600
1494602678249	geckodriver::marionette	TRACE	  connection attempt 13/600
1494602678354	geckodriver::marionette	TRACE	  connection attempt 14/600
1494602678470	geckodriver::marionette	TRACE	  connection attempt 15/600
1494602678576	geckodriver::marionette	TRACE	  connection attempt 16/600
1494602678682	geckodriver::marionette	TRACE	  connection attempt 17/600
1494602678783	geckodriver::marionette	TRACE	  connection attempt 18/600
1494602678887	geckodriver::marionette	TRACE	  connection attempt 19/600
1494602678992	geckodriver::marionette	TRACE	  connection attempt 20/600
1494602679097	geckodriver::marionette	TRACE	  connection attempt 21/600
1494602679201	geckodriver::marionette	TRACE	  connection attempt 22/600
1494602679305	geckodriver::marionette	TRACE	  connection attempt 23/600
1494602679410	geckodriver::marionette	TRACE	  connection attempt 24/600
1494602679516	geckodriver::marionette	TRACE	  connection attempt 25/600
1494602679620	geckodriver::marionette	TRACE	  connection attempt 26/600
1494602679724	geckodriver::marionette	TRACE	  connection attempt 27/600
1494602679828	geckodriver::marionette	TRACE	  connection attempt 28/600
1494602679933	geckodriver::marionette	TRACE	  connection attempt 29/600
1494602679946	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1494602679947	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1494602679948	Marionette	INFO	Listening on port 54095
1494602680050	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:54095
1494602680080	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:54190
1494602680089	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1494602680089	geckodriver::marionette	TRACE	→ 185:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},"marionette":true,"nativeEvents":true}]
1494602680095	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"nativeEvents":true}},"marionette":true,"nativeEvents":true}]
1494602680103	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":10908,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.SmMCcaf5LSdS","moz:accessibilityChecks":false}
1494602680290	Marionette	DEBUG	loaded listener.js
1494602680307	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"67f30df8-0573-e94c-a21b-16764561d6be","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":10908,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.SmMCcaf5LSdS","moz:accessibilityChecks":false}}]
1494602680314	geckodriver::marionette	TRACE	← [1,1,null,{"sessionId":"67f30df8-0573-e94c-a21b-16764561d6be","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"15.6.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":10908,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.SmMCcaf5LSdS","moz:accessibilityChecks":false}}]
1494602680315	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"67f30df8-0573-e94c-a21b-16764561d6be","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":10908,"moz:profile":"/var/folders/pg/2xh7xdhs5l91lfpcw7mvyp2h0000gn/T/rust_mozprofile.SmMCcaf5LSdS","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"15.6.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1494602680326	webdriver::server	DEBUG	→ POST /session/67f30df8-0573-e94c-a21b-16764561d6be/url {"url":"http://localhost:3001/a"}
1494602680327	geckodriver::marionette	TRACE	→ 45:[0,2,"get",{"url":"http://localhost:3001/a"}]
1494602680413	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://localhost:3001/a"}]
2017-05-12 08:24:40.428 plugin-container[10911:212064] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-12 08:24:40.436 plugin-container[10911:212064] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa20b, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-12 08:24:40.438 plugin-container[10911:212064] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
1494602680526	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1494602680588	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1494602680589	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1494602680672	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://localhost:3001/a"
1494602680682	Marionette	DEBUG	Received DOM event "pageshow" for "http://localhost:3001/a"
1494602680701	Marionette	TRACE	0 <- [1,2,null,{}]
1494602680749	geckodriver::marionette	TRACE	← [1,2,null,{}]
1494602680749	webdriver::server	DEBUG	← 200 OK {"value": {}}
2017-05-12 08:24:40.890 plugin-container[10912:212110] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x5143, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-12 08:24:40.891 plugin-container[10912:212110] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9e23, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-12 08:24:40.891 plugin-container[10912:212110] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
1494602681766	webdriver::server	DEBUG	→ POST /session/67f30df8-0573-e94c-a21b-16764561d6be/elements {"using":"css selector","value":"html > body > a"}
1494602681766	geckodriver::marionette	TRACE	→ 71:[0,3,"findElements",{"using":"css selector","value":"html > body > a"}]
1494602681768	Marionette	TRACE	0 -> [0,3,"findElements",{"using":"css selector","value":"html > body > a"}]
1494602681776	Marionette	TRACE	0 <- [1,3,null,[{"element-6066-11e4-a52e-4f735466cecf":"acd501d4-1d2c-8843-82aa-5883db08d78c","ELEMENT":"acd501d4-1d2c-8843-82aa-5883db08d78c"}]]
1494602681777	geckodriver::marionette	TRACE	← [1,3,null,[{"element-6066-11e4-a52e-4f735466cecf":"acd501d4-1d2c-8843-82aa-5883db08d78c","ELEMENT":"acd501d4-1d2c-8843-82aa-5883db08d78c"}]]
1494602681777	webdriver::server	DEBUG	← 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"acd501d4-1d2c-8843-82aa-5883db08d78c"}]}
1494602681781	webdriver::server	DEBUG	→ POST /session/67f30df8-0573-e94c-a21b-16764561d6be/element/acd501d4-1d2c-8843-82aa-5883db08d78c/click {}
1494602681781	geckodriver::marionette	TRACE	→ 66:[0,4,"clickElement",{"id":"acd501d4-1d2c-8843-82aa-5883db08d78c"}]
1494602681783	Marionette	TRACE	0 -> [0,4,"clickElement",{"id":"acd501d4-1d2c-8843-82aa-5883db08d78c"}]
1494602682063	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
1494602682065	Marionette	TRACE	0 <- [1,4,null,{}]
1494602682066	geckodriver::marionette	TRACE	← [1,4,null,{}]
1494602682066	webdriver::server	DEBUG	← 200 OK {"value": {}}
navigate back
1494602683076	webdriver::server	DEBUG	→ POST /session/67f30df8-0573-e94c-a21b-16764561d6be/back {}
1494602683077	geckodriver::marionette	TRACE	→ 17:[0,5,"goBack",{}]
1494602683078	Marionette	TRACE	0 -> [0,5,"goBack",{}]
1494602983087	Marionette	TRACE	0 <- [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:213:5\nTimeoutError@chrome://marionette/content/error.js:463:5\nnotify@chrome://marionette/content/listener.js:297:17\n"},null]
1494602983089	geckodriver::marionette	TRACE	← [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:213:5\nTimeoutError@chrome://marionette/content/error.js:463:5\nnotify@chrome://marionette/content/listener.js:297:17\n"},null]
1494602983100	webdriver::server	DEBUG	← 408 Request Timeout {"value":{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"stack backtrace:\n   0:        0x105a2b82e - backtrace::backtrace::trace::h76b688ec9dd0c4e2\n   1:        0x105a2bf6c - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:        0x1059de9cf - webdriver::error::WebDriverError::new::h7184d15bc5556898\n   3:        0x1059eeffb - geckodriver::marionette::MarionetteSession::response::h3a41c0cc62e59c56\n   4:        0x1059ece93 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::hcb53484f0f6d535e\n   5:        0x1059dee60 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::he6d10c2fe3c7e795\n   6:        0x1059b4a5d - std::panicking::try::do_call::hd7b79b66c427c537\n   7:        0x105b56d1a - __rust_maybe_catch_panic\n   8:        0x1059c179a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hde402662965177dc\n   9:        0x105b55174 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f\n  10:     0x7fff96d4699c - _pthread_body\n  11:     0x7fff96d46919 - _pthread_start"}}
Error: TimeoutError: Timeout loading page after 300000ms
1494602983105	webdriver::server	DEBUG	→ DELETE /session/67f30df8-0573-e94c-a21b-16764561d6be
1494602983105	geckodriver::marionette	TRACE	→ 48:[0,6,"quitApplication",{"flags":["eForceQuit"]}]
1494602983108	Marionette	TRACE	0 -> [0,6,"quitApplication",{"flags":["eForceQuit"]}]
1494602983111	Marionette	INFO	New connections will no longer be accepted
1494602983195	Marionette	TRACE	0 <- [1,6,null,{"cause":"shutdown"}]
1494602983221	geckodriver::marionette	TRACE	← [1,6,null,{"cause":"shutdown"}]
1494602983221	webdriver::server	DEBUG	Deleting session
1494602983221	geckodriver::marionette	DEBUG	Stopping browser process
** Unknown exception behavior: -2147483647
** Unknown exception behavior: -2147483647
1494602983749	webdriver::server	DEBUG	← 200 OK {"value": {}}
```

> 1494602682063	Marionette	DEBUG	Canceled page load listener because no navigation has been detected

I assume this is when webdriver clicked the link, and the browser *did* show the new page (b.html). Please note that Turbolinks doesn't do the whole normal full page network request/page load/render, it fetches the body of the new page and render it in place, and changes other states like browser history accordingly.

**Comment by hudson-t** [comment]
@whimboo - I am also having an issue invoking driver.navigate().back() in Protractor. I am keen to give the GeckoDriver nightly build a try but I cannot seem to be able to find the source code to build it? Got it building from master? Is that correct?

**Comment by andreastt** [comment]
@hudson-t The fix for this bug resides in the Marionette remote protocol, which lives inside Firefox. You will need to test with the latest _Firefox_.

**Comment by hudson-t** [comment]
@andreastt - thanks for this. Where can I access the logs for Marionette remote driver? I am still having the issue even with the latest Nightly build and wanted to check "goBack" is being triggered.

**Comment by whimboo** [comment]
@KSKS what kind of element is acd501d4-1d2c-8843-82aa-5883db08d78c in your case? Is it a delayed loading of a URL? Maybe Turbolinks is causing this? I assume that we fail because of the early return from `click()`.

**Comment by whimboo** [comment]
@hudson-t, you have to specify the tracing output in the capabilities, see our documention here, or set `--log trace` for geckodriver. Then you can find the logs in geckodriver.log.

**Comment by KSKS** [comment]
@whimboo I think acd501d4-1d2c-8843-82aa-5883db08d78c is the link <a> to the second page (b.html), which I simply click (element.click()) in the script. I am not sure what you mean by delayed loading of a URL. The test did go to the second page before I called driver.navigate().back().

**Comment by whimboo** [comment]
Please see the line right after `clickElement`:

>1494602682063	Marionette	DEBUG	Canceled page load listener because no navigation has been detected

Here we escape the logic of waiting for the page being loaded, because no `unload` event happened within a 200ms time frame. It means whether the browser was running unusually slow, or something delayed the page load as issued by the click. I wish a minimized testcase would be available here. Please check if a workaround like waiting for an element of the target page before calling `back` works. I'm pretty sure it will.

**Comment by whimboo** [comment]
And I just had a look at the [Turbolinks Github repository](https://github.com/turbolinks/turbolinks). Here the following is stated:

```
When you follow a link, Turbolinks automatically fetches the page, swaps in its <body>, and merges its <head>, all without incurring the cost of a full page load.
```

So it looks like that this tool is doing an inline replacement of the full document. The page load is magically done in some loaded Javascript code - most likely via AJAX. So there is nothing we can do for click + page load in this case.

**Comment by whimboo** [comment]
So I tested this locally with the attached example files which I missed earlier. And I can see that the problem is exactly what I mentioned before. There is not a single page load event fired. So not sure what kind of magic this library is doing with the session history in Firefox. Basically all the navigation in the history has to fire events as described here:

https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching

If that is not happening Marionette will not handle that in `back`.

So whether this is a problem in Turbolinks, or Firefox itself. But it doesn't seem to be an issue with Marionette/Geckodriver.

@AutomatedTester, I assume that we can close this issue?

**Comment by AutomatedTester** [comment]
Yes, unfortunately. There is not much we can do here.

**Comment by KSKS** [comment]
I don't think this issue should be closed just yet. Even in the case that Marionette/Geckodriver couldn't detect there is a page load/navigation, the promise returned from calling `back` should resolve (in Javascript binding). Looking at the geckodiver log, it looks like Marionette didn't response to the `back` request from webdriver, could this be the reason the promise not resolving?
```
1494602683076	webdriver::server	DEBUG	→ POST /session/67f30df8-0573-e94c-a21b-16764561d6be/back {}
1494602683077	geckodriver::marionette	TRACE	→ 17:[0,5,"goBack",{}]
1494602683078	Marionette	TRACE	0 -> [0,5,"goBack",{}]
1494602983087	Marionette	TRACE	0 <- [1,5,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:213:5\nTimeoutError@chrome://marionette/content/error.js:463:5\nnotify@chrome://marionette/content/listener.js:297:17\n"},null]
```

If I call `back` on a page with no previous browser history, the promise would resolve properly, the geckodriver in this case shows:
```
1496099388455	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/6d3f337f-e960-ca43-b330-99c0d04c8cc0/back")
1496099388456	webdriver::command	DEBUG	Got request body {}
1496099388456	geckodriver::marionette	DEBUG	→ 17:[0,3,"goBack",{}]
1496099388458	Marionette	TRACE	0 -> [0,3,"goBack",{}]
1496099388460	Marionette	TRACE	0 <- [1,3,null,{}]
1496099388462	geckodriver::marionette	DEBUG	← [1,3,null,{}]
1496099388462	webdriver::server	DEBUG	Returning status Ok
1496099388462	webdriver::server	DEBUG	Returning body {"value": {}}
```

Another question: Do you know what events are needed minimally for Marionette to detect a navigation, so I can ask Turbolinks about it? It looks like 5 events are fired when Turbolinks is not used while going back in history: `beforeunload`, `pagehide`, `unload` `DOMContentLoaded`, `pageshow`. Are all 5 events needed for Marionette to detect a navigation? or does it only need a subset of it?

**Comment by whimboo** [comment]
> If I call back on a page with no previous browser history, the promise would resolve properly, the geckodriver in this case shows

That is correct. Without having a page in the history for backward or forward navigation, the appropriate command will return immediately. We do not wait for any events, which also will not occur. 

> It looks like 5 events are fired when Turbolinks is not used while going back in history: beforeunload, pagehide, unload DOMContentLoaded, pageshow. Are all 5 events needed for Marionette to detect a navigation? or does it only need a subset of it?

I would suggest you to have a look at the bfcache article on MDN. It explains exactly which events are fired. So `beforeunload` will always happen and indicates that a page is about to get unloaded. We also always wait for `DOMContentLoaded` because it indicates that the DOM structure has been completely loaded. For `pageshow` we do not always wait. It depends on the page load strategy. In case of `eager` we already abort when `DOMContentLoaded` has been received. Otherwise we wait for `pageshow`, which indicates that all referenced resources have also been loaded.

I hope that answers your questions.

**Comment by KSKS** [comment]
Thanks for answering my questions. I took a look at W3C WebDriver Standard (https://www.w3.org/TR/webdriver), the [back](https://www.w3.org/TR/webdriver/#back) command says that if there is `pagehide` event, it should wait for a `pageshow` event (or until timeout) in step 4. But since there isn't a `pagehide` event in this case, should Marionette return success as in step 6?

**Comment by whimboo** [comment]
Hm, good question. @AutomatedTester can you please have a look? Maybe the spec is not valid in this case? Or should we also have a unload timer similar to `click()`?

**Comment by KSKS** [comment]
@AutomatedTester is there any update? Should we keep this issue open for now?

**Comment by whimboo** [comment]
I will reopen until we got a clear statement from @AutomatedTester.

**Comment by whimboo** [comment]
So this is most likely happen because the page you are testing is manipulating the history of the browser via pushState() and replaceState(). There is [bug 1386977](https://bugzilla.mozilla.org/show_bug.cgi?id=1386977) I'm working on now.

See also issue #815 for a similar or the same issue.

**Comment by whimboo** [comment]
Issue #815 is fixed now with the upcoming Nightly build of Firefox today. @KSKS, can you please have a look later today, if your specific issue is also fixed? Thanks.

**Comment by whimboo** [comment]
Closing as dupe of #815 for now because I think it is the same underlying issue.
